MOONWORLD: Fix compiler warning.
Fix for

cc1plus: warnings being treated as errors
indra/newview/llviewerobjectlist.cpp: In member function
‘void LLViewerObjectList::updateApparentAngles(LLAgent&)’:
indra/newview/llviewerobjectlist.cpp:642:34: error:
operation on ‘((LLViewerObjectList*)this)->LLViewerObjectList::mCurBin’
may be undefined

which happens since g++ version 4.5.